import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/Provider";

export const metadata: Metadata = {
  title: "EaseKart — Shop quick, eat fresh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-[#F25A1A] to-[#F7F2D7] w-full h-screen">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
